# Copyright (c) 2026. All rights reserved.
# Financial Audit Environment — Task definitions.
#
# Each task defines:
#   - A unique ID and human-readable name
#   - Difficulty level (easy / medium / hard)
#   - A description that the agent reads to understand what to audit
#   - Maximum steps allowed before the episode auto-ends
#   - The set of valid error_types the agent can report
#   - The data generator function name to use
#
# Tasks are designed for a clear difficulty progression:
#   Easy   → single-document policy checks (expense claims)
#   Medium → cross-document matching (PO vs GRN vs Invoice)
#   Hard   → cross-system reconciliation (Books vs GSTR-2B)

from typing import Any, Dict, List


# ---------------------------------------------------------------------------
# Task 1: Expense Policy Violation Detection (Easy)
# ---------------------------------------------------------------------------
TASK_EXPENSE_AUDIT = {
    "id": "expense_audit",
    "name": "Expense Policy Violation Detection",
    "difficulty": "easy",
    "description": (
        "You are an internal auditor reviewing employee expense claims against "
        "the company's expense policy.\n\n"
        "Your job is to identify expenses that violate company policy. "
        "You will be given:\n"
        "1. A list of expense claims with fields: expense_id, date, employee, "
        "category, amount, description, receipt_id, vendor\n"
        "2. The company's expense policy with rules and limits\n\n"
        "For each violation found, report:\n"
        "- document_id: the expense_id of the violating entry\n"
        "- error_type: one of the allowed violation types\n"
        "- description: explain what the violation is\n"
        "- suggested_fix: what action should be taken\n\n"
        "Be thorough — find ALL violations. But be precise — false positives "
        "will lower your score."
    ),
    "max_steps": 5,
    "error_types": [
        "over_limit",         # Amount exceeds category limit
        "wrong_category",     # Expense miscategorized
        "duplicate_claim",    # Same receipt submitted twice
        "weekend_expense",    # Business expense on weekend without approval
        "missing_receipt",    # No receipt for expense over threshold
        "unapproved_vendor",  # Vendor not on approved list
    ],
    "generator": "generate_expense_data",
}

# ---------------------------------------------------------------------------
# Task 2: Invoice Three-Way Match Audit (Medium)
# ---------------------------------------------------------------------------
TASK_INVOICE_MATCH = {
    "id": "invoice_match",
    "name": "Invoice Three-Way Match Audit",
    "difficulty": "medium",
    "description": (
        "You are a procurement auditor performing a three-way match between "
        "Purchase Orders (POs), Goods Receipt Notes (GRNs), and Vendor Invoices.\n\n"
        "The three-way match ensures:\n"
        "- What was ordered (PO) matches what was received (GRN)\n"
        "- What was invoiced matches what was ordered and received\n"
        "- Prices, quantities, tax rates, and totals are consistent\n\n"
        "You will be given:\n"
        "1. Purchase Orders: po_id, vendor, items with unit_price and quantity\n"
        "2. Goods Receipt Notes: grn_id, po_id, items received with quantities\n"
        "3. Vendor Invoices: invoice_id, po_id, vendor, line items, tax, total\n\n"
        "For each discrepancy found, report:\n"
        "- document_id: the invoice_id (or po_id/grn_id if relevant)\n"
        "- error_type: one of the allowed discrepancy types\n"
        "- description: explain the discrepancy with specific numbers\n"
        "- suggested_fix: recommended resolution"
    ),
    "max_steps": 8,
    "error_types": [
        "price_mismatch",      # Invoice price ≠ PO agreed price
        "quantity_mismatch",   # Invoiced qty ≠ received qty
        "duplicate_invoice",   # Two invoices for same PO/line
        "unmatched_invoice",   # Invoice with no corresponding PO
        "tax_error",           # Incorrect GST rate applied
        "total_mismatch",      # Line items don't sum to total
        "vendor_mismatch",     # Invoice vendor ≠ PO vendor
        "date_anomaly",        # Invoice dated before PO or GRN
    ],
    "generator": "generate_invoice_data",
}

# ---------------------------------------------------------------------------
# Task 3: GST Return Reconciliation (Hard)
# ---------------------------------------------------------------------------
TASK_GST_RECONCILIATION = {
    "id": "gst_reconciliation",
    "name": "GST Return Reconciliation",
    "difficulty": "hard",
    "description": (
        "You are a tax auditor reconciling a business's Purchase Register "
        "(internal books) against GSTR-2B data (auto-generated by the "
        "government GST portal based on suppliers' filings).\n\n"
        "Mismatches between books and GSTR-2B can cause:\n"
        "- Loss of Input Tax Credit (ITC) if claimed but not in GSTR-2B\n"
        "- Missed ITC if in GSTR-2B but not recorded in books\n"
        "- Penalties for incorrect claims\n\n"
        "You will be given:\n"
        "1. Purchase Register entries: invoice_no, vendor_name, vendor_gstin, "
        "date, taxable_value, cgst, sgst, igst, total, hsn_code, place_of_supply\n"
        "2. GSTR-2B entries: supplier_gstin, invoice_no, date, taxable_value, "
        "igst, cgst, sgst, total\n\n"
        "For each mismatch found, report:\n"
        "- document_id: the invoice_no from either dataset\n"
        "- error_type: one of the allowed mismatch types\n"
        "- description: explain the mismatch with specific values\n"
        "- suggested_fix: recommended action (e.g., 'contact supplier to file', "
        "'reverse ITC claim')\n\n"
        "Key rules:\n"
        "- Intra-state supply uses CGST + SGST; inter-state uses IGST\n"
        "- GSTIN format: 2-digit state code + 10-char PAN + 1 entity + 1 check digit\n"
        "- ITC cannot be claimed for invoices older than 180 days\n"
        "- Certain categories (food & beverages, personal vehicles) have blocked ITC"
    ),
    "max_steps": 10,
    "error_types": [
        "missing_in_gstr2b",   # In books but supplier hasn't filed
        "missing_in_books",    # In GSTR-2B but not in purchase register
        "amount_mismatch",     # Taxable value differs
        "tax_rate_mismatch",   # CGST/SGST/IGST rates differ
        "gstin_mismatch",      # Vendor GSTIN doesn't match supplier GSTIN
        "date_mismatch",       # Invoice date differs by > 30 days
        "duplicate_entry",     # Same invoice appears twice in books
        "invalid_gstin",       # GSTIN fails format validation
        "wrong_tax_type",      # IGST for intra-state (should be CGST+SGST) or vice versa
        "itc_ineligible",      # Blocked ITC category
        "late_claim",          # Invoice > 180 days old
        "excess_claim",        # ITC amount > GSTR-2B amount
    ],
    "generator": "generate_gst_data",
}


# ---------------------------------------------------------------------------
# Task registry — maps task_id to definition
# ---------------------------------------------------------------------------
TASKS: Dict[str, Dict[str, Any]] = {
    "expense_audit": TASK_EXPENSE_AUDIT,
    "invoice_match": TASK_INVOICE_MATCH,
    "gst_reconciliation": TASK_GST_RECONCILIATION,
}


def get_task(task_id: str) -> Dict[str, Any]:
    """
    Retrieve a task definition by ID.

    Args:
        task_id: One of 'expense_audit', 'invoice_match', 'gst_reconciliation'

    Returns:
        Task definition dictionary

    Raises:
        ValueError: If task_id is not recognized
    """
    if task_id not in TASKS:
        valid = ", ".join(TASKS.keys())
        raise ValueError(
            f"Unknown task_id: '{task_id}'. Valid options: {valid}"
        )
    return TASKS[task_id]


def get_all_tasks_summary() -> List[Dict[str, Any]]:
    """
    Return a summary of all tasks for the /tasks endpoint.

    Returns list of dicts with: id, name, difficulty, description, max_steps,
    error_types (the allowed values for Finding.error_type).
    """
    return [
        {
            "id": t["id"],
            "name": t["name"],
            "difficulty": t["difficulty"],
            "description": t["description"],
            "max_steps": t["max_steps"],
            "error_types": t["error_types"],
            "action_schema": {
                "findings": [
                    {
                        "document_id": "string (required)",
                        "field": "string (optional)",
                        "error_type": f"string — one of {t['error_types']}",
                        "description": "string (required)",
                        "suggested_fix": "string (optional)",
                    }
                ],
                "submit_final": "boolean (default: false)",
            },
        }
        for t in TASKS.values()
    ]
